In [1]:
# LAB 1: Welcome to Machine Learning
# Student name: MD Tanvir Hossain Rumon
# Student ID: 20245103137
print("Hello, future ML detective!")
print("Rule 1: The computer is literal, not rude.")

Hello, future ML detective!
Rule 1: The computer is literal, not rude.

* Write one sentence explaining what the error message helped you identify.

The error message helped me identify that I had a syntax error caused by a missing quotation mark, so I corrected the quotation mark and ran the code again.

In [2]:
import numpy as np

np.random.seed(42)

marks = np.array([55, 72, 48, 90, 66, 81])

print('Marks:', marks)

print('Mean:', marks.mean())

print('Highest:', marks.max())

print('Passed:', marks[marks >= 50])

Marks: [55 72 48 90 66 81]
Mean: 68.66666666666667
Highest: 90
Passed: [55 72 90 66 81]

12. Find the minimum mark and standard deviation.

In [3]:
print('Minimum:', marks.min())
print('Standard Deviation:', marks.std())

Minimum: 48
Standard Deviation: 14.372040758206733

13. Add 5 bonus marks to every student without changing the original array.

In [4]:
bonus_marks = marks + 5
print('Bonus Marks:', bonus_marks)
print('Original Marks:', marks)

Bonus Marks: [60 77 53 95 71 86]
Original Marks: [55 72 48 90 66 81]

14. Count how many students passed.

In [5]:
passed_count = np.sum(marks >= 50)
print('Number of Passed Students:', passed_count)

Number of Passed Students: 5

15. Create a 2 × 3 matrix from the marks.

In [6]:
matrix = marks.reshape(2, 3)
print('2 × 3 Matrix:')
print(matrix)

2 × 3 Matrix:
[[55 72 48]
 [90 66 81]]

In [8]:
import pandas as pd

data = {
    'student': ['Asha', 'Babu', 'Chayan', 'Dipa', 'Emon', 'Farah'],
    'study_hours': [2, 5, 1, 7, 3, 6],
    'sleep_hours': [8, 6, 9, 5, 7, 6],
    'attendance': [70, 88, 55, 95, 75, 91],
    'snacks': [3, 2, 5, 1, 4, 2],
    'passed': ['Yes', 'Yes', 'No', 'Yes', 'No', 'Yes']
}

df = pd.DataFrame(data)

Ans No 16

In [9]:
features = ['study_hours', 'sleep_hours', 'attendance', 'snacks']
label = 'passed'

print("Features:", features)
print("Label:", label)

Features: ['study_hours', 'sleep_hours', 'attendance', 'snacks']
Label: passed

17. How many samples and columns are present?

In [10]:
print("Number of samples:", df.shape[0])
print("Number of columns:", df.shape[1])

Number of samples: 6
Number of columns: 6

18. Filter students with attendance of at least 80.

In [11]:
print("\nStudents with attendance >= 80:")
display(df[df['attendance'] >= 80])

Students with attendance >= 80:

  student  study_hours  sleep_hours  attendance  snacks passed
1    Babu            5            6          88       2    Yes
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes

19. Calculate average study hours for students who passed.

In [12]:
average_study = df[df['passed'] == 'Yes']['study_hours'].mean()
print("\nAverage study hours of passed students:", average_study)

Average study hours of passed students: 5.0

20. Sort the DataFrame by attendance in descending order.

In [13]:
print("\nSorted by attendance:")
display(df.sort_values(by='attendance', ascending=False))

Sorted by attendance:

  student  study_hours  sleep_hours  attendance  snacks passed
3    Dipa            7            5          95       1    Yes
5   Farah            6            6          91       2    Yes
1    Babu            5            6          88       2    Yes
4    Emon            3            7          75       4     No
0    Asha            2            8          70       3    Yes
2  Chayan            1            9          55       5     No

21. Does this tiny dataset prove that snack purchases cause failure?

No. This dataset does not prove that snack purchases cause failure.

For example, Chayan bought 5 snacks and failed, but Emon bought 4 snacks and also failed. However, that does not establish that snacks caused their failure.

There are several reasons:

Only 6 students are included.
This is observational data, not a controlled experiment.
Other factors such as study hours, attendance, and sleep may affect the result.
Correlation does not necessarily mean causation.
A much larger and properly designed study would be needed to investigate whether snack purchases are associated with academic outcomes.

* Run the cell twice. Record which outputs remain identical. Then explain: if two groups claim different
accuracies because they used different random splits, can we fairly compare their models?

In [14]:
import random
import numpy as np

def generate_scores(use_seed):
    if use_seed:
        random.seed(42)
        np.random.seed(42)

    return np.random.randint(40, 101, size=5)

print('Seeded run 1:', generate_scores(True))
print('Seeded run 2:', generate_scores(True))
print('Unseeded run 1:', generate_scores(False))
print('Unseeded run 2:', generate_scores(False))

Seeded run 1: [78 91 68 54 82]
Seeded run 2: [78 91 68 54 82]
Unseeded run 1: [ 47 100  60  78  97]
Unseeded run 2: [58 62 50 50 63]

Same model + different random split → different accuracy can occur.


Same split + same evaluation procedure → much fairer model comparison.